### ISSUE TITLE
Exception thrown for Cart Rule

### ISSUE THREAD

**Issue by selwynorren** [thirtybees/mailchimp#10]
Hey Michael,
Something interesting happened today. I created a cart rule for a May promo I am running. after I created the promo I saw that there was a Mailchimp column. naturally I could not resist clicking it, which threw an exception at me.

Property MailChimpModule\MailChimpPromo->locked is empty
at line 1022 in file classes/ObjectModel.php

Is this a feature not yet implemented or my configuration all wrong?

**Comment by firstred** [comment]
Strange. The fields should default to `false`, but that does not happen. Looks like a bug to me.

**Comment by firstred** [comment]
Turns out the `locked` property was missing at the top of the `MailChimpPromo` file.

You have to define it at the top first: `public $locked`, otherwise thirty bees will not set the default value.

Thanks for the report, will release a new version soon!

**Comment by selwynorren** [comment]
Oh awesome, This is great news - lol Again thanks for all your hard work

**Comment by selwynorren** [comment]
Just wanted to check with you. I just logged in now and noticed that the tawk.to and mailchimp module had updates ready. I clicked update, however tawk.to no problem, but mailchimp I had to click twice to update. Then when I repeated what I initially did I am still getting the same exception error.

Do you think I should uninstall and re-install a fresh copy of the module?

**Comment by firstred** [comment]
The module has had a few updates, but none fix this exception, yet.

**Comment by selwynorren** [comment]
k perfect, ill hang on - lol

**Comment by firstred** [comment]
Fixed now. Closing.
