### ISSUE TITLE
Problem when syncing customers

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/mailchimp#7]
When I sync one of my stores I see the following:
![export](https://user-images.githubusercontent.com/15154932/32008160-d36afb22-b9ab-11e7-9673-d75aaad04d77.JPG)

The number is wrong. It should be 1266 for this shop. Morever the sync is failing somehow. In my list I get the following:
![sync-problem](https://user-images.githubusercontent.com/15154932/32008288-25d1f3ca-b9ac-11e7-8d2f-c92b124e2bd7.JPG)

As you can see only 159 customers were sent.

Version: 1.0.3, PHP 7.0.24, MySQL 10.2.8-MariaDB

**Comment by firstred** [comment]
Does 1.2.0 beta 4 solve it?

**Comment by firstred** [comment]
Issue solved?

**Comment by eschiendorfer** [comment]
Yes its solved!
