### ISSUE TITLE
Critical multistore bug when syncing customers

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/mailchimp#8]
I noticed a critical bug, when you sync customers with multistore. In one store I have 22 subscribers (customers = 51). After syncing I got 58 customers in my mailchimp list! This is not possible. I checked them a bit. Some of them are customers from other shops!

TB Version 1.0.3 and Module Version 1.1.3

**Comment by firstred** [comment]
I'll be damned :open_mouth: 

Are you on Slack?

**Comment by firstred** [comment]
```php
$sql->leftJoin(bqSQL(self::$definition['table']), 'mc', 'mc.`id_cart` = c.`id_cart`');
$sql->where('c.`id_shop` = '.(int) $idShop);
```

That doesn't look like it will apply the filter properly. Sending you a new version in a minute.

**Comment by firstred** [comment]
wrong file, but it's the same restriction everywhere.

**Comment by firstred** [comment]
Hmmz, yet it does filter properly. Strange...

**Comment by eschiendorfer** [comment]
Could you find the problem?

**Comment by firstred** [comment]
Not yet.

**Comment by firstred** [comment]
How are the results after the latest update?

**Comment by firstred** [comment]
Does 1.2.0 beta 4 solve it?

**Comment by eschiendorfer** [comment]
Just tried to new install the module. When I add an api key. I get: **cURL error 6: Could not resolve host: -us9.api.mailchimp.com; Name or service not known (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)**  
 *at line* **186** *in file* `vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php`

**Comment by firstred** [comment]
That's annoying, I thought mailchimp padded the data center number with zeros.
Thanks for the info, tho.

**Comment by firstred** [comment]
Can you try and see if this version works?

[mailchimp-v1.2.0-DC_HOTFIX.zip](https://github.com/thirtybees/mailchimp/files/1924602/mailchimp-v1.2.0.zip)

**Comment by eschiendorfer** [comment]
yep now its saving!

**Comment by firstred** [comment]
Original issue solved as well?

**Comment by eschiendorfer** [comment]
Yes, seems to be solved!
